### ISSUE TITLE
Not sure how to use the library with multiple JSON schema files

### ISSUE THREAD

**Issue by AlexTo** [edgarmueller/schema-validator-web#4]
Hi
I am trying to validate my JSON with TinCan JSON schema from here 

[TinCan Schema](https://github.com/RusticiSoftware/TinCanSchema)

As you can see in folder `1.0.1` there are several json files reference each other. 

And now, I may have a `Statement` object like this

    {
        "actor": {...} // actor can be either Agent or Group and validated by Agent.json or Group.json
        "verb": {...}
        "object": {...}
    }

How can I build a validator from several json schema files?

Thank you

**Comment by edgarmueller** [comment]
I'm closing this one this is tracked in https://github.com/eclipsesource/play-json-schema-validator/issues/135 already and this repo only contains the code for the web frontend. But if you should have questions, feel free to ask.
